### ISSUE TITLE
ICNS Tracking Issue

### ISSUE THREAD

**Issue by mattverse** [icns-xyz/icns#1]
### Resolver 
- [x] #2
- [x] #5
- [x] [Create Msg for setting addresses for given bech32 prefixes(this should be called by Registrar)](https://github.com/interchain-name/icns/commit/c1a1a5550b3c0ddd0b2e4384f0679fc8507c12a0)
- [x] [validate bech32 address](https://github.com/interchain-name/icns/commit/123795f92a0f46ac2f6f2e4b7ca94a9faab87e16)
- [x]  [Have a check for ensuring user name does not contain `.`](https://github.com/interchain-name/icns/commit/123795f92a0f46ac2f6f2e4b7ca94a9faab87e16)
- [x] Rename `SetAddresses` to `SetRecord`
- [ ] Make resolver msgs a package and make them generic
- [ ] store `name_address`
- [ ] checks owner from name on performing `set_record`

### Registry
- [x] Make Resolver address state a Vector field: Discussed with Tony, decision made to leave as a single field for now
- [x] [Change Regitrar address in config from Vec to single field](https://github.com/interchain-name/icns/commit/c1a1a5550b3c0ddd0b2e4384f0679fc8507c12a0)
- [x] #3
- [x] #4
- [x] [Deprecate `SetRecord` and change it to `SetResolverAddrs`](https://github.com/interchain-name/icns/commit/c1a1a5550b3c0ddd0b2e4384f0679fc8507c12a0)
- [x] #8
- [x] #6

### Registrar
- [x] [Change `Admin` field in the Config to `Operator`](https://github.com/interchain-name/icns/commit/123795f92a0f46ac2f6f2e4b7ca94a9faab87e16)
- [ ] Add message(query) for calling the msg in the resolver to set address for given bech32 prefix
- [x] #7
- [x] [Change Addr from Addr to String inside Msg](https://github.com/interchain-name/icns/commit/123795f92a0f46ac2f6f2e4b7ca94a9faab87e16)
- [x] #10
- [x] #12

### Name NFT
- [x] rename `name` to `name_nft`
- [x] allow `registrar` to transfer `name` as part of the registration process
- [x] move `resolver_addresses` state to `name`

### Testing
- [x] #9

### Migration
- [ ] enable migrations for all contracts

------
### V2
- [ ] Create a separate contract to manage Admin
- [ ] Bech 32 verification
